name:                haskix-hs
version:             0.1.0.0
github:              "haskix/haskix-hs"
license:             MIT

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.8 && < 3
- mtl >= 2.2 && < 3
- megaparsec >= 9.2 && < 10
- hspec-megaparsec >= 2.2 && < 3
- containers >= 0.6 && < 1
- string-interpolate >= 0.3 && < 1

default-extensions:
- DataKinds
- TypeFamilies
- StandaloneDeriving

library:
  source-dirs: src

tests:
  haskix-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskix-hs
    - hspec >= 2.8 && < 3
