name:                haskix-hs
version:             0.1.0.0
github:              "haskix/haskix-hs"
license:             MIT

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  haskix-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskix-hs
